### ISSUE TITLE
Buenas prácticas para proyectos OSS

### ISSUE THREAD

**Issue by cr0hn** [T1GR3S/airo-Heat#2]
Sería deseable seguir las buenas prácticas para proyectos OSS publicados.

Se puede encontrar un guía en: https://opensource.guide

A modo de resumen, sería deseable que el proyecto tuviera los siguientes archivos, en caso de no tenerlos, (con el contenido adecuado):

- CONTRIBUTING
- LICENSE
- README
- .gitignore
- ISSUE_TEMPLATE/issue_template.md
- TODO

Del mismo modo, sería deseable (en caso de no tenerlo) que el repositorio tuviera:
- *labels* a modo de palabras clave del mismo.
- Una descripción del proyecto

**Comment by ricardojoserf** [comment]
Hola @cr0hn, hemos añadido el fichero .gitignore, actualizado el README (no se encuentra en su versión final aún) y hemos añadidos alguna label.

Un saludo y muchas gracias

**Comment by ricardojoserf** [comment]
Buenas @cr0hn, acabamos de crear la licencia.

Un saludo y gracias!

**Comment by cr0hn** [comment]
Os falta la plantilla para issues

**Comment by silvianerea** [comment]
Hola @cr0hn , ya hemos creado la plantilla para issues
Un saludo y gracias!
