### ISSUE TITLE
Ficheros de debug y configuración de IDE

### ISSUE THREAD

**Issue by cr0hn** [T1GR3S/airo-Heat#3]
Es una mala práctica y no deberían de estar subidos al repositorios binarios, ficheros de depuración o configuración del IDE.

<img width="713" alt="airo-heat_airo-heat-tool_at_master_ _t1gr3s_airo-heat" src="https://user-images.githubusercontent.com/4076390/49290817-599dd880-f4a8-11e8-8067-c96141a23702.png">

**Comment by ricardojoserf** [comment]
Hola @cr0hn, hemos añadido las rutas en el fichero .gitignore. Esperemos que lo solucione. Al ser un repositorio con muchas tecnologías distintas no hemos podido usar un .gitignore de los que te ofrece Github por defecto, aunque tampoco sea excusa.

Gracias!

**Comment by cr0hn** [comment]
Aunque estén el fichero de .gitignore, tendréis que borrarlos del repositorio git y subir los cambios a Github

**Comment by ricardojoserf** [comment]
Hola @cr0hn , ya lo hemos solucionado.

Muchas gracias!
