### ISSUE TITLE
Valores harcodeados en el código fuente

### ISSUE THREAD

**Issue by cr0hn** [T1GR3S/airo-Heat#5]
No es buena práctica especificar los valores de conexión de la base de datos en el código fuente, aunque esta conexión apunte a un fichero SQLite3:

<img width="807" alt="airo-heat_server_js_at_master_ _t1gr3s_airo-heat" src="https://user-images.githubusercontent.com/4076390/49291918-0cbc0100-f4ac-11e8-85fc-199d3c1b8eff.png">

**Comment by ricardojoserf** [comment]
Hola @cr0hn , hemos añadido un fichero de configuración config.js en esa parte, aunque sigue viéndose el nombre de la base de datos en dicho fichero, por lo que lo añadiremos al .gitignore.

Muchas gracias y un saludo

**Comment by cr0hn** [comment]
En el config.js, la información ahora se obtiene por variables de entorno y, aunque tenga valor por defecto, no está mal. Cierro el issue
