### ISSUE TITLE
Base de datos en Github

### ISSUE THREAD

**Issue by cr0hn** [T1GR3S/airo-Heat#6]
Salvo buena justificación, la base de datos  no debería de estar en Github:

<img width="673" alt="airo-heat_backend-dev_node_server_at_master_ _t1gr3s_airo-heat" src="https://user-images.githubusercontent.com/4076390/49291979-3e34cc80-f4ac-11e8-9dd9-3afa228e2588.png">

**Comment by ricardojoserf** [comment]
Buenas @cr0hn, la acabamos de borrar. Configurando con la línea "*.db" el .gitignore creemos que lo solucionará para el futuro.

Muchas gracias de nuevo
